# Generated by Django 5.0.1 on 2024-01-31 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='events',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=80)),
                ('event_description', models.CharField(max_length=1000)),
                ('event_date', models.DateField()),
                ('event_contact', models.CharField(max_length=50)),
            ],
        ),
    ]
