# Generated by Django 4.2.7 on 2024-02-04 18:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Gri',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_number', models.CharField(max_length=15)),
                ('address', models.TextField()),
                ('grievance_category', models.CharField(max_length=50)),
                ('other_category', models.CharField(blank=True, max_length=50)),
                ('grievance_description', models.TextField()),
                ('attachment', models.FileField(blank=True, upload_to='attachments/')),
                ('preferred_resolution', models.CharField(max_length=20)),
                ('submit_date', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
