# Generated by Django 5.0.1 on 2024-02-07 15:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaintApp', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Griv',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_number', models.CharField(max_length=15)),
                ('address', models.TextField()),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], default='male', max_length=10)),
                ('grievance_category', models.CharField(choices=[('road_conditions', 'Road Conditions'), ('water_supply', 'Water Supply'), ('electricity', 'Electricity'), ('payment_issues', 'Payment Issues'), ('noise_disputes', 'Noise Disputes'), ('other', 'Other (please specify)')], max_length=20)),
                ('grievance_description', models.TextField()),
                ('attachment', models.FileField(blank=True, null=True, upload_to='attachments/')),
                ('preferred_resolution', models.CharField(choices=[('immediate_resolution', 'Immediate resolution'), ('investigation_required', 'Investigation required'), ('follow_up_required', 'Follow-up required')], max_length=30)),
                ('target_language', models.CharField(choices=[('en', 'English'), ('mr', 'Marathi'), ('hi', 'Hindi')], default='en', max_length=2)),
                ('status', models.IntegerField(choices=[(0, 'Pending'), (1, 'Resolved')], default=0)),
                ('submit_date', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Gri',
        ),
    ]
