# Generated by Django 5.0.1 on 2024-01-31 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='saveService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(max_length=100)),
                ('service_description', models.CharField(max_length=1000)),
                ('service_contact', models.CharField(max_length=50)),
            ],
        ),
    ]
